
#Tomcat Server
server:
  port: 8081
  error.include-stacktrace: always
  
# Logger  
logging.level:
  web: DEBUG  
  '[com.simplilearn.spring]': DEBUG
  
spring:
  #Database Settings 
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 
    
    
---

# AWS Configuration    

server:
  port: 8081

spring:
  config:
    activate.on-profile: aws    

# Database Settings
  datasource:
    url: jdbc:mysql://simplilearn-rds.cpsmk2cgceb2.us-west-2.rds.amazonaws.com:3306/mydb
    username: admin
    password: admin123